language: node_js
node_js: node
services:
    - mongodb
cache:
  directories:
    - node_modules

deploy:
provider: heroku
api_key:
  secure: TeUTJcwtwM3kOEkZf6NEomfD3Oe/BUYpMWTcZ670qFcG4YBNTr88H+8qrnEbYqx6O028kTkjCI2KBYtESZ/Lg7ItmLXvH1IsVswJp2DlbcFoeeLsMLB6IH7rjcND5tCgHKhQvfwnWYkL/68SCA8e/6cRmp1AXGdkRzzfm9+1uP/V5Q0ShFWX1MfzK+l3QF8MyV4Iye81XWOiFGp/YrfSKSWapZxcrlG5TbqS/bcrhWrSZ/s5vcbEWPvxkXwclTx2AZ4ykgqzum158QJpAz/ao54pnhW2dQDycb3o1UsZpe8cIYptNx7//1qd1z6MCVti92BLXUKB5uxeV048sQ3j9mvWAq6kW2Mdc8U7UONCPSLpBOrsoJohYYVJWT4yQqvfZhzYTQY2Hlzy8pe4naFwoDwO3fExnPpMNcs8ccWVKOdl00rWwbmWGHNlrFukPfXg7WN2wfLLCv0dcoguNwfP9+cTuBHrRzCJp1PmtEe6iwVEkbpgSDjD0u2rNZWiNu7KdA7Q7UiPqG6T2OPND0rJr3gvQvG02ihoEw/M3P+oPb31H7oz3RdQ4GZD/03J1ZDesOlpBKp9N/V3SJ5mMoC+NgkMU0dAqLJiuJCNdOo7f94jDdsUWxihz263OSBBJbl89/ARGGlh+m+z2tIcC/ctNab3h5X7SyXUoH9PNkVVp6E=
app: secret-harbor-24537
on: 
  repo: Carenelizabeth/money-jars-server